/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author nitro5WIN10
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        
        setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        labelUsuarioPrivilegio = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnNotificacoes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        textUsuarioMenuBar = new javax.swing.JMenu();
        menuNovoUsuario = new javax.swing.JMenuItem();
        menuVisualizarTodosUsuario = new javax.swing.JMenuItem();
        menuAutorizacaoPendente = new javax.swing.JMenuItem();
        textNotificacoesMenuBar = new javax.swing.JMenu();
        menuNovaNotificacao = new javax.swing.JMenuItem();
        menuVisualizarTodasNotificacoes = new javax.swing.JMenuItem();
        textConfiguracaoMenuBar = new javax.swing.JMenu();
        menuConta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        btnNotificacoes.setText("Notificações");

        jMenuBar1.setToolTipText("");

        textUsuarioMenuBar.setText("Usuários");

        menuNovoUsuario.setText("Novo");
        textUsuarioMenuBar.add(menuNovoUsuario);

        menuVisualizarTodosUsuario.setText("Visualizar todos");
        textUsuarioMenuBar.add(menuVisualizarTodosUsuario);

        menuAutorizacaoPendente.setText("Autorização pendente");
        textUsuarioMenuBar.add(menuAutorizacaoPendente);

        jMenuBar1.add(textUsuarioMenuBar);

        textNotificacoesMenuBar.setText("Notificações");

        menuNovaNotificacao.setText("Novo");
        textNotificacoesMenuBar.add(menuNovaNotificacao);

        menuVisualizarTodasNotificacoes.setText("Visualizar todas");
        textNotificacoesMenuBar.add(menuVisualizarTodasNotificacoes);

        jMenuBar1.add(textNotificacoesMenuBar);

        textConfiguracaoMenuBar.setText("Configuração");

        menuConta.setText("Conta");
        textConfiguracaoMenuBar.add(menuConta);

        jMenuBar1.add(textConfiguracaoMenuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNotificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelUsuarioPrivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUsuarioPrivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNotificacoes)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLabelUsuarioPrivilegio() {
        return labelUsuarioPrivilegio;
    }

    public JMenu getTextConfiguracaoMenuBar() {
        return textConfiguracaoMenuBar;
    }

    public JMenu getTextNotificacoesMenuBar() {
        return textNotificacoesMenuBar;
    }

    public JMenu getTextUsuarioMenuBar() {
        return textUsuarioMenuBar;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public JMenuItem getMenuConta() {
        return menuConta;
    }

    public JMenuItem getMenuNovaNotificacao() {
        return menuNovaNotificacao;
    }

    public JMenuItem getMenuNovoUsuario() {
        return menuNovoUsuario;
    }

    public JMenuItem getMenuVisualizarTodasNotificacoes() {
        return menuVisualizarTodasNotificacoes;
    }

    public JMenuItem getMenuVisualizarTodosUsuario() {
        return menuVisualizarTodosUsuario;
    }

    public JMenuItem getMenuAutorizacaoPendente() {
        return menuAutorizacaoPendente;
    }

    public JButton getBtnNotificacoes() {
        return btnNotificacoes;
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNotificacoes;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelUsuarioPrivilegio;
    private javax.swing.JMenuItem menuAutorizacaoPendente;
    private javax.swing.JMenuItem menuConta;
    private javax.swing.JMenuItem menuNovaNotificacao;
    private javax.swing.JMenuItem menuNovoUsuario;
    private javax.swing.JMenuItem menuVisualizarTodasNotificacoes;
    private javax.swing.JMenuItem menuVisualizarTodosUsuario;
    private javax.swing.JMenu textConfiguracaoMenuBar;
    private javax.swing.JMenu textNotificacoesMenuBar;
    private javax.swing.JMenu textUsuarioMenuBar;
    // End of variables declaration//GEN-END:variables
}
